workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Install Gradle 9.3.1
        script: |
          wget https://services.gradle.org/distributions/gradle-9.3.1-bin.zip
          unzip -q gradle-9.3.1-bin.zip
          export PATH="$PWD/gradle-9.3.1/bin:$PATH"
          gradle --version

      - name: Create debug keystore
        script: |
          keytool -genkeypair \
            -v \
            -keystore "$CM_BUILD_DIR/debug.keystore" \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US" \
            || true

      - name: Build Release APK
        script: |
          export PATH="$PWD/gradle-9.3.1/bin:$PATH"
          gradle assembleRelease

    artifacts:
      - app/build/outputs/apk/release/*.apk


  android-aab:
    name: Android AAB Build
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Install Gradle 9.3.1
        script: |
          wget https://services.gradle.org/distributions/gradle-9.3.1-bin.zip
          unzip -q gradle-9.3.1-bin.zip
          export PATH="$PWD/gradle-9.3.1/bin:$PATH"
          gradle --version

      - name: Create debug keystore
        script: |
          keytool -genkeypair \
            -v \
            -keystore "$CM_BUILD_DIR/debug.keystore" \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US" \
            || true

      - name: Build Release AAB
        script: |
          export PATH="$PWD/gradle-9.3.1/bin:$PATH"
          gradle bundleRelease

    artifacts:
      - app/build/outputs/bundle/release/*.aab
